run:
  skip-dirs:
    - pkg/curlator
linters:
  enable-all: true
  disable:
    - wsl
    - wrapcheck
    - varnamelen
    - gci
    - exhaustivestruct
    - exhaustruct
    - gomnd
    - gofmt

    # to be fixed:
    - ireturn
    - gosec
    - noctx
    - funlen
    - nestif
    - interfacer
    - revive
    - cyclop
    - goerr113
    - gocognit

    # deprecated:
    - scopelint
    - deadcode
    - varcheck
    - maligned
    - ifshort
    - nosnakecase
    - structcheck
    - golint
